MAX_NUMBER_RULES = 20

BASE_ITERATION_LIMIT = 500

ITERATION_REDUCTION_TIME = 0.7

CRITERION_WEIGHTS = [5, 5, 2]

CONTROL_OPTIMIZATION_ITERATION = 20

TIME_STEP_SIMULATION = 0.0025
TIME_SIMULATION = 3

FLAG_TIME_NO_CONTACT = 2
FLAG_TIME_SLIPOUT = 0.8