MAX_NUMBER_RULES = 6

BASE_ITERATION_LIMIT = 500

ITERATION_REDUCTION_TIME = 0.7

CRITERION_WEIGHTS = [3, 1, 3, 4, 5]

CONTROL_OPTIMIZATION_ITERATION = 20
TIME_OPTIMIZATION = 100

TIME_STEP_SIMULATION = 0.0025
TIME_SIMULATION = 3

FLAG_TIME_NO_CONTACT = 1.5
FLAG_TIME_SLIPOUT = 0.4