version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
    - mamba activate rostok

conda:
  environment: environment.yml

sphinx:
  configuration: docs/conf.py

python:
  install:
  - method: pip
    path: .