MAX_NUMBER_RULES = 20

BASE_ITERATION_LIMIT = 50

ITERATION_REDUCTION_TIME = 0.7

CRITERION_WEIGHTS = [3, 1, 3, 4, 5]

CONTROL_OPTIMIZATION_ITERATION = 3

TIME_STEP_SIMULATION = 0.0025
TIME_SIMULATION = 10

FLAG_TIME_NO_CONTACT = 5
FLAG_TIME_SLIPOUT = 0.8