MAX_NUMBER_RULES = 15

BASE_ITERATION_LIMIT = 30
BASE_ITERATION_LIMIT_GRAPH = 200

ITERATION_REDUCTION_TIME = 0.7

TIME_CRITERION_WEIGHT = 1
FORCE_CRITERION_WEIGHT = 1
OBJECT_COG_CRITERION_WEIGHT = 1
INSTANT_FORCE_CRITERION_WEIGHT = 1
INSTANT_CONTACTING_LINK_CRITERION_WEIGHT = 1
GRASP_TIME_CRITERION_WEIGHT = 1
FINAL_POSITION_CRITERION_WEIGHT = 10
REFERENCE_DISTANCE = 20

CONTROL_OPTIMIZATION_BOUNDS = (6, 15)
CONTROL_OPTIMIZATION_ITERATION = 3

TIME_STEP_SIMULATION = 0.0025
GRASP_TIME = 5
FORCE_TEST_TIME = 5
TIME_SIMULATION = 10

FLAG_TIME_NO_CONTACT = 1
FLAG_TIME_SLIPOUT = 0.5
FLAG_FLYING_APART = 10